- src/index.js
- test/index.js
Relevant conversation on:
1. https://chat.zulip.org/#narrow/stream/bots/topic/zulip-js.20api.20bindings
2. https://chat.zulip.org/#narrow/stream/test.20here/topic/github-issues
> realm-name: Add support for realm urls having '/api' at the end.

- package.json
- src/api.js
- src/helper.js
- src/resources/accounts.js
- test/common.js
- test/resources/accounts.js
tests: Replace accounts.js tests with standalone tests.
Stubs the fetch and formdata modules to get standalone testing done.
Also, wraps the above modules in a helper module so that it becomes
an object and can be stubbed with sinon. Without this, it is not
possible to stub them.
@timabbott @showell  please take a look once and tell me if this approach looks good. I was planning on trying to get this repository ready for GCI.
> Proof of concept standalone tests.

- examples/subscriptions.js
- src/resources/users.js
- test/resources/users.js
The endpoint to view existing subscriptions was in `zulip.streams.subscriptions.retrieve()` and since it didn't match the actual endpoint `/users/me/subscriptions`, I added this to the `zulip.users.me.subscriptions.add()` endpoint instead.
Added an example file to show usage. Since the testing framework is not exactly functional right now, didn't write any tests. I was working on mocking some stuff on a separate branch, would push that soon in another PR.
Sorry for the delay here. Hope it isn't too late. Fixes #14
> api: Add POST /users/me/subscriptions endpoint. Fixes #14.

- src/resources/messages.js
- test/resources/messages.js
Fixes #22. Adds support for passing the data directly as a String as well
as using a JSON object like {content: "Message Here"}.
> api: Add messsages/render endpoint.

- examples/call_endpoint.js
- package.json
- src/index.js
- test/common.js
- test/index.js
- test/zuliprc
Fixes #21.
Had to disable eslint in two cases for 1. trying to enforce camel case and 2. trying to not let modify function parameters.
> api: Expose the call_endpoint method for generic API calls.

- README.md
- examples/queues.js
- src/resources/queues.js
- test/resources/queues.js
This commit adds a method called queues.deregister that allows
one to call the `DELETE /api/v1/events` endpoint and delete a
previously registered queue.
Fixes #29.
@aero31aero FYI :) This is the first time I've ever written anything in JavaScript lol
> queues.js: Add deregister method.

- test/index.js
- test/resources/accounts.js
- test/resources/emojis.js
- test/resources/events.js
- test/resources/messages.js
- test/resources/queues.js
- test/resources/streams.js
- test/resources/typing.js
- test/resources/users.js
Previously, there was a huge error in the test framework that even
chai threw an error and reected the promise, we didn't catch it and
fail the test. Instead, it just logged an unhandled Promise rejection
warning in the console. Thus, any failing tests of promises could be
detected only by looking at the tests when running them. This PR
fixes this for two of the files.
Also, as a minor fix, we now check for the HTTP method as well in the
requests being made in these two files.
Files updates: test/index.js and test/resources/accounts.js.
>  tests: Improve failure reporting by using then-catch.

- src/resources/users.js
- test/resources/users.js
/users/me/getProfile is not a valid URL.
@aero31aero: FYI
@Balaji2198: The URL you used when writing this method was invalid. I would recommend always testing your code locally with a running Zulip server instance and making an API request before submitting a PR. The problem with this repo is that it isn't automatically tested against a running Zulip instance (I plan on fixing this soon-ish), so we have to be very careful when writing new methods! :)
> users: Use correct URL for API request.

- examples/accounts.js
- examples/call_endpoint.js
- examples/emojis.js
- examples/events.js
- examples/init.js
- examples/messages.js
- examples/private-messages.js
- examples/queues.js
- examples/streams.js
- examples/typing-notifications/send.js
- examples/users.js
This updates all the examples we use, to look similar to /api docs.
Fixes #41.
> examples: Use apiKey instead of password in config.

- package.json
Some bundlers including Browserify[1] and Parcel[2] use the browser field in package.json to ignore modules (using browser-resolve[3]) that do not work well with browsers.
In our case this is the zuliprc related module, fs-readfile-promise.
This commit adds a browser field with fs-readfile-promise set to false to the package.json, so that clients that are bundled with Browserify or Parcel can use zulip-js out of the box.
1: https://github.com/browserify/browserify-handbook#browser-field
2: https://github.com/parcel-bundler/parcel/issues/200
3: https://github.com/defunctzombie/node-browser-resolve
> Add browser field to package.json to ignore fs-readfile-promise

- README.md
- examples/users.js
- src/resources/users.js
- test/resources/users.js
This is a WIP PR to update https://github.com/zulip/zulip-js/pull/15 with the new style of tests etc.
The old comments are:
> This PR adds support to update a user's pointer, to move the home view. This lets you mark a message as read. This has a side effect of marking some messages as read.
> The usage is zulip.users.me.pointer.update(id) where id is the message id (or the current value of the pointer + 1).
> 
> This is a work in progress, and review/feedback would be appreciated!
> WIP: add support to update pointer

- README.md
- examples/messages.js
- src/resources/messages.js
- test/resources/messages.js
This is a WIP continuation of https://github.com/zulip/zulip-js/pull/16, to use the new test / README style. The old comments are below:
> This is a work in progress to mark messages as read (among other things), thanks to @timabbott's helpful comment on the update pointer PR:
> 
> > More importantly, this isn't the right endpoint for marking something as read; this is the endpoint for moving the home view (which has a side effect of making some things read).
>  >
> > You want /messages/flags, and I would definitely implement it as the bulk operation, since that's almost always what one wants.
> 
> As always, feedback would be super helpful.
> 
> One thing that would be great is to have an description for the various flags - I think read/starred are pretty self-explanatory, the others …
> WIP add support for bulk adding/removing a flag to messages

- README.md
- examples/reactions.js
- src/index.js
- src/resources/reactions.js
- test/resources/reactions.js
This PR adds support to add or remove an emoji reaction to a message. 
The usage is `zulip.reactions.add({ message_id: 1, emoji: smile })` and `zulip.reactions.remove({ message_id: 1, emoji: smile })`
This is a work in progress, and review/feedback would be appreciated!
> WIP: add support to add/remove reactions

- package.json
This PR adds support for git installs. Installing from a git url is useful to test development branches/PRs. 
This is achieved by using https://github.com/exogen/postinstall-build 
The build script is only run on post install if the build artifact does not exist (ie., it will not run on an npm install).
Note that this renames the compile script to build (and updates the prepublish script)
> Support git installs

- README.md
Updating README to use syntax using Promises. Readme example was written like this,
```
const zulip = require('zulip-js')(config);
zulip.streams.subscriptions().then(res => {
console.log(res);
}); 
```
It should be updated to latest syntax using javascript promises, like this,
```
zulip(config).then(zulip => {
// The zulip object now initialized with config
zulip.streams.subscriptions().then(res => {
console.log(res);
});
});
```
> Updating README to use syntax using Promises

- README.md
- examples/reactions.js
- src/resources/reactions.js
- test/resources/reactions.js
Update the reactions code to use the new API.
1. The url is `/messages/<message_id>/reactions`
2. The parameters are `emoji_code`, `emoji_name` (only required for `POST`) and `reaction_type` (default is `unicode_emoji`)
See @timabbott's comment: https://github.com/zulip/zulip-js/pull/50#issuecomment-370241630
https://github.com/zulip/zulip/blob/master/zproject/urls.py
```
url(r'^messages/(?P<message_id>[0-9]+)/reactions$',                                              
rest_dispatch,                                                                               
{'POST': 'zerver.views.reactions.add_reaction',                                              
'DELETE': 'zerver.views.reactions.remove_reaction'}),   
```
https://github.com/zulip/zulip/blob/master/zerver/views/reactions.py
```
def …
```
> Use new reactions API

- src/resources/messages.js
- src/resources/queues.js
- src/resources/streams.js
- src/resources/typing.js
- test/resources/messages.js
- test/resources/typing.js
JavaScript handles any object assignation by reference. This caused objects used as parameters being unexpectedly modified, resulting in unwanted behavior.
Includes fixes in the tests that should avoid future regressions.
> code: Deep copy all modified parameter objects.

- README.md
- examples/messages.js
- src/resources/messages.js
- test/resources/messages.js
> Add endpoint for GET message history by Id.

- README.md
- examples/server.js
- src/index.js
- src/resources/server.js
- test/resources/server.js
> Add endpoint to get server settings.

- package-lock.json
- package.json
Commit 58211431c5020986d561cc77ebf1f5b4353836ca removed the configuration but not the package itself. Really fixes #72.
> package: Finish removing deprecated postinstall-build package

- README.md
- src/resources/streams.js
- test/resources/streams.js
added endpoint to delete stream by stream id
CC #63
> Add endpoint for DELETE /streams/<stream_id>

- README.md
The example snippets weren't valid.
One would get a reference error when trying to make use of it.
`ReferenceError: Cannot access 'zulip' before initialization`
> Remove README collision

- examples/call_endpoint.js
- examples/events.js
- examples/interactive_call_endpoint.js
- examples/messages.js
- examples/private-messages.js
- examples/subscriptions.js
- examples/typing-notifications/send-and-recieve.js
- examples/typing-notifications/send-often.js
- examples/typing-notifications/send.js
- examples/users.js
- package-lock.json
- package.json
- src/api.js
- src/events_wrapper.js
- src/index.js
- test/index.js
- test/resources/reactions.js
- test/resources/streams.js
- test/resources/users.js
Generated using the usual `npm outdated` process.
Hopefully, merging this will close all the dependabot PR spam.
> dependencies: Upgrade dependencies.
